# Generated by Django 4.2 on 2026-06-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
