# Generated by Django 4.2 on 2026-06-04 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTV', '0002_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowManager',
        ),
    ]
