# Generated by Django 4.2 on 2026-05-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0002_ninjas_dojo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
