# Generated by Django 4.2 on 2026-05-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BAS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
