# Generated by Django 4.2 on 2026-05-30 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BAS', '0002_authors_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors_has_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAS.authors')),
                ('the_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BAS.book')),
            ],
        ),
        migrations.AddField(
            model_name='authors',
            name='the_book',
            field=models.ManyToManyField(through='BAS.Authors_has_books', to='BAS.book'),
        ),
    ]
