# Generated by Django 4.2 on 2026-06-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
