# Generated by Django 5.2.7 on 2025-11-12 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0006_alter_game_relese_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='relese_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
